export const FLOW_TRANSLATOR_BASE_URL = import.meta.env
  .VITE_FLOW_TRANSLATOR_BASE_URL

export const KEIP_ASSISTANT_DOCS_URL = import.meta.env
  .VITE_KEIP_ASSISTANT_DOCS_URL

export const KEIP_ASSISTANT_OLLAMA_URL = import.meta.env
  .VITE_KEIP_ASSISTANT_OLLAMA_URL

export const K8S_CLUSTER_URL = import.meta.env.VITE_KEIP_ASSISTANT_K8S_CLUSTER_URL
